title: mmmint.ai - building smart solutions
baseurl: /
permalink: "/:year/:month/:day/:title/"
collections:
  posts:
    permalink: "/blog/:year/:month/:day/:title/"

header:
  title: mmmint.ai
  logo_img: images/logo.png
  has_nav: true
  nav:
    Home: "index"
    Blog: "blog"
    Solutions: "solutions"
    Workshops: "workshops"
    Team: "about"
  palette: blue
  menu:
    actions:
      - label: Sign Up
        url: /signup
footer:
  logo_img: images/logo_alt.png
  tagline: mmmint.ai - building smart solutions
  content: "&copy; MMM Intelligence UG (haftungsbeschränkt). All rights reserved."
  links:
    - text: Impressum
      url: "/impressum"
      new_window: false

  social_title: Community

  nav_title: Company
  nav:
    Home: "index"
    Blog: "blog"
    Solutions: "solutions"
    Workshops: "workshops"
    Career: "career"
    About: "about"

  has_subscribe: true
  subscribe_title: "Subscribe"
  subscribe_content: "Melde dich jetzt bei unserem Newsletter an und bleibe immer auf dem neuesten Stand. Wir berichten als Start-Up rund um KI & Digitales."

sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
